# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe670b174313523c87cada43329ee36c15f2de8dccbf7ae6a8cca1e5c03b05065e47ae92258e4886c82c4449e1336e1c120f77a8375c84c94d375c33fae11324

test:
  secret_key_base: e7d7e8e7194e60aa0263314730ead3170cf3ebbe19aec4346f83eca262a3aadc7352d716bc8d895c45fbee7e2e00e22ad8b5adb7ef67c81a1cfbe9c5cb66e006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
